# Generated by Django 6.0.3 on 2026-05-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
    ]
